name: Build BLE HID Keyboard

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: arm-zephyr-eabi

      - name: Build Firmware
        run: |
          west build -b holyiot_yj17095 app --pristine -- -DCONF_FILE=prj.conf

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: zephyr-ble-hid-keyboard
          path: build/zephyr/zephyr.hex
          retention-days: 30
